### Gerando access token (Direct Grant ou Resource Owner Password Credentials Grant)
POST http://localhost:8080/realms/fullcycle-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=psgvaz@gmail.com
&password=123
&grant_type=password
&client_id=fullcycle-client


### Gerando access token e id token
POST http://localhost:8080/realms/fullcycle-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=psgvaz@gmail.com
&password=123
&grant_type=password
&client_id=fullcycle-client
&scope=openid

### authorization code flow
POST http://localhost:8080/realms/fullcycle-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&client_id=fullcycle-client
&code=abda4746-d1b0-4bbc-895b-d492b6b97d21.d8559b5f-59eb-4ff6-91b8-f5d5c962b487.0dd57284-01cc-487a-a60d-f3153a228074
&redirect_uri=http://localhost:3000/callback